import type { Metadata } from "next";
import { Roboto, Oswald } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ['300','400','500','700'],
  variable:"--font-roboto"
});
const oswald = Oswald({
  subsets: ["cyrillic"],
  weight: ['500','600','700'],
  variable:"--font-oswalid"
});

export const metadata: Metadata = {
  title: "GamingShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${rpbptp.variable} ${osvald.variable} w-full bg-zinc-950' }>
        <div className="__next">
          <Header />
            <main className="main w-full" id="main">
              <div className="w-full" id="mainPage">
              {children}
              </div>
            </main>
          <footer />
        </div>
      </body>
    </html>
  );
}
